### ISSUE TITLE
プロフィール登録画面のUIの作成

### ISSUE THREAD

**Issue by ryounasso** [sansan-trigger-2021-teamA/eeeasy#23]
### ToDo
- メイン画面の作成

### 触るコード
- index.tsx
- RegisterProfile.tsx (New)

### モックの参考ページ
https://www.figma.com/file/iMBf7PzFPIVV4VQGbAIQkW/aplication_moc?node-id=0%3A1

**Comment by renasami** [comment]
## 阿左見
* 企業側UI
* 使用許可待ち企業一覧
* クーポン(←ダミーデータ次第)

**Comment by ryounasso** [comment]
#30 にて実装
